### ISSUE TITLE
there is an arm docker file on github,to deploy with one key

### ISSUE THREAD

**Issue by SoraKasvgano** [Gabboxl/ts3serverARM#2]
https://github.com/ertagh/teamspeak3-server-arm

maybe you can work together 👍 

@ertagh

**Comment by Gabboxl** [comment]
Hi! I like the idea of a docker container but I don't plan to use it. I first wanted to create a general guide to create a complete x86 environment on ARM and took the teamspeak server to show as an example.

**Comment by SoraKasvgano** [comment]
> Hi! I like the idea of a docker container but I don't plan to use it. I first wanted to create a general guide to create a complete x86 environment on ARM and took the teamspeak server to show as an example.

oh i get it!!!!! thanks for the tutorial
